DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 8
  TEST:
    BATCH_SIZE: 100
  NUM_WORKERS: 8

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]

OPTIM:
  NAME: "sgd"
  LR: 0.005
  MAX_EPOCH: 10
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 1
  WARMUP_TYPE: "constant"
  WARMUP_CONS_LR: 1e-5

TRAIN:
  PRINT_FREQ: 20
  CHECKPOINT_FREQ: 1

MODEL:
  BACKBONE:
    NAME: "ViT-B/16"

TRAINER:
  SUPR:
    N_CTX_VISION: 4
    N_CTX_TEXT: 4
    CTX_INIT: "a photo of a"
    PREC: "fp16"
    PROMPT_DEPTH_VISION: 3
    PROMPT_DEPTH_TEXT: 3
    SPACE_DIM: 2
    ENSEMBLE_NUM: 3
    REG_LOSS_WEIGHT: 60
    LAMBDA: 0.5
    HARD_PROMPT_PATH: "configs/trainers/SuPr/hard_prompts/"
    TRAINER_BACKBONE: "SuPr"
    SVD: False # use least square save gpu memory(mathematical equivalent)

